### ISSUE TITLE
Boot splash

### ISSUE THREAD

**Issue by odessky** [igorpecovnik/Lime-Debian#2]
Does your Lime Debian is support boot splash via plymouth?

**Comment by igorpecovnik** [comment]
No, plymouth is not configured and it's not working out of the box.

I made one script to achieve similar but it's not perfect:
https://github.com/igorpecovnik/lib/blob/next/scripts/bootsplash

It must be possible:
https://groups.google.com/forum/#!topic/beagleboard/DhMw7cMkimk

**Comment by odessky** [comment]
Thanks, bootsplash script is good for me.
